version: '2'
services:
    btcd:
      image: gcr.io/whiteblock/btc-lightning/btcd:master
      container_name: btcd
      entrypoint: ["./start-btcd.sh"]
    lnd:
      image: gcr.io/whiteblock/btc-lightning/lnd:master
      container_name: lnd
      entrypoint: ["./start-lnd.sh"]
      links:
        - "btcd:blockchain"